ParadiseBookers/ParadiseBookers.Web/Models/Properties/PropertyViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Data.Spatial;
using ParadiseBookers.Core.Common.Geography;
using ParadiseBookers.Core.Model;
using ParadiseBookers.Dropdowns.Attributes;
using ParadiseBookers.Models.Common;

namespace ParadiseBookers.Models.Properties
{
    public class PropertyViewModel
    {
        public PropertyViewModel()
        {
            Location = new AddressModel()
                {
                    Address = "301 15th Street, Hood River",
                    Location = GeographyHelpers.CreatePoint(45.7120903, -121.5272902)
                };
        }

        public string Name { get; set; }

        public AddressModel Location { get; set; }

        [Display(Name = "Bedrooms")]
        public int BedRooms { get; set; }

        [Display(Name = "Bathrooms")]
        public int BathRooms { get; set; }

        [Display(Name = "Sleeps")]
        public int Sleeps { get; set; }

        [Display(Name = "Pets Allowed?")]
        public bool PetsAllowed { get; set; }

        [Display(Name = "Cable TV?")]
        public bool CableTv { get; set; }

        [Display(Name = "DVD Player?")]
        public bool DvdPlayer { get; set; }

        [Display(Name = "Pool?")]
        [EnumDropDown(typeof(PoolType))]
        public PoolType Pool { get; set; }

        public int FloorArea { get; set; }

        // kitchen stuff
        [Display(Name = "Full Kitchen?")]
        public bool FullKitchen { get; set; }

        [Display(Name = "Refrigerator")]
        public bool Refrigerator { get; set; }

        [Display(Name = "Refrigerator")]
        public bool CoffeeMaker { get; set; }

        public bool Microwave { get; set; }

        public bool Cookware { get; set; }

        public bool Dishwasher { get; set; }

        public bool Oven { get; set; }

        // living stuff
        [Display(Name = "Central Air")]
        public bool CentralAir { get; set; }

        [Display(Name = "Ceiling Fans")]
        public bool CeilingFans { get; set; }

        public bool Linens { get; set; }

        [Display(Name = "Washer And Dryer?")]
        public bool WasherAndDryer { get; set; }

        public bool Wifi { get; set; }

        [Display(Name = "24/7 Security")]
        public bool TwentyFourSecurity { get; set; }

        [Display(Name = "Elevator")]
        public bool Elevator { get; set; }

        [Display(Name = "Towels")]
        public bool Towels { get; set; }

        [Display(Name = "Phone")]
        public bool Phone { get; set; }

        [EnumDropDown(typeof(FurninishingType))]
        public FurninishingType Furninishing { get; set; }

        // location stuff
        [Display(Name = "Beach Nearby?")]
        public bool BeachNearby { get; set; }

        [Display(Name = "Beach Distance (Miles)")]
        public int BeachDistanceMiles { get; set; }
    }
}

ParadiseBookers/ParadiseBookers.Web/Controllers/Properties/PropertiesController.cs
using System.Linq;
using System.Web.Mvc;
using ParadiseBookers.Core.Interfaces.Service;
using ParadiseBookers.Core.Model;
using ParadiseBookers.Models.Properties;
using Omu.ValueInjecter;
namespace ParadiseBookers.Controllers.Properties
{
    public class PropertiesController : Controller
    {
        private readonly IPropertyService PropertyService;

        public PropertiesController(IPropertyService service)
        {
            PropertyService = service;
        }

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Properties/        
        public ActionResult Manager(int page = 1, int pageSize = 10)
        {
            var model = PropertyService.GetAll().ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new PropertyViewModel());
        }

        [HttpPost]
        public ActionResult Create(PropertyViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var model = new Property();

                model.InjectFrom<UnflatLoopValueInjection>(viewModel);

                PropertyService.CreateProperty(model);

                return RedirectToAction("Manager");
            }
           

            return View(viewModel);
        }

        public ActionResult Photos(int id)
        {
            var property = PropertyService.GetByID(id);
            var model = new PropertyViewModel().InjectFrom<UnflatLoopValueInjection>(property);
            return View(model);
        }

        public ActionResult Websites(int id)
        {
            var property = PropertyService.GetByID(id);
            var model = new PropertyViewModel().InjectFrom<UnflatLoopValueInjection>(property);
            return View(model);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var property = PropertyService.GetByID(id);
            var model = new PropertyViewModel().InjectFrom<UnflatLoopValueInjection>(property);
            return View(model);
        }

        [HttpGet]
        public ActionResult Rates(int id)
        {
            var property = PropertyService.GetByID(id);
            var model = new PropertyViewModel().InjectFrom<UnflatLoopValueInjection>(property);
            return View(model);
        }

        public ActionResult Promote(int id)
        {
            var property = PropertyService.GetByID(id);
            var model = new PropertyViewModel().InjectFrom<UnflatLoopValueInjection>(property);
            return View(model);
        }
    }
}

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Create.cshtml
@{
    ViewBag.Title = "Create";
    Bundles.Reference("googleMaps");
    Layout = "~/Views/Shared/Basic.cshtml";   
}

@section AltNav
{
    <div class="pull-right">
        <a class="btn btn-large" href="@Url.Action("Manager")">Cancel</a>
    </div>
}

@model ParadiseBookers.Models.Properties.PropertyViewModel

@using (Html.BeginForm("Create", "Properties", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true, "Unable to save property. Please correct the errors and try again.", new { @class = "alert alert-block alert-error" })

    @Html.EditorForModel()

    <div class="form-actions">
        <input type="submit" value="Save" class="btn btn-inverse btn-large" />
    </div>
}

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Details.cshtml
@{
    ViewBag.Title = "Details";
    Bundles.Reference("googleMaps");
}


@model ParadiseBookers.Models.Properties.PropertyViewModel

@using (Html.BeginForm("Update", "Properties", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true, "Unable to save property. Please correct the errors and try again.", new { @class = "alert alert-block alert-error" })

    @Html.EditorForModel()

    <div class="form-actions">
        <input type="submit" value="Save" class="btn btn-inverse btn-large" />
    </div>
}

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Basic.cshtml";
}
@section LeftColumn
{
    <ul class="nav nav-tabs nav-stacked">

        <li>
            <a href="@Url.Action("Profile", "Account")">User Account</a>
        </li>
        <li>
            <a href="@Url.Action("Settings", "Account")">Change Password</a>
        </li>
    </ul>
}

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Manager.cshtml
@{
    Layout = "~/Views/Shared/Basic.cshtml";
}
@model IList<ParadiseBookers.Core.Model.Property>

@section AltNav
{
    <div class="pull-right">
        <a href="@Url.Action("Create", "Properties")" class="btn btn-large">
            <i class="icon-plus"></i>
            New Property
        </a>
    </div>

}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Title</th>
            <th>Owner</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var property in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Details", "Properties", new { id = property.Id })">@property.Id</a>
                </td>
                <td>
                    @property.Name
                </td>
                <td>
                    <a href="#">sancho</a>
                </td>
            </tr>
        }

    </tbody>
</table>

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Photos.cshtml
@{
    ViewBag.Title = "Photos";    
}

<h2>Photos</h2>

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Promote.cshtml
@{
    ViewBag.Title = "Promote";
}

<form class="">

    <div class="controls">
        <button class="btn btn-primary">
            Post to AirBNB
        </button>
    </div>
    <br/>
    <div class="controls">
        <button class="btn btn-primary">
            Post to Craigslist
        </button>
    </div>
    <br/>
     <div class="controls">
        <button class="btn btn-primary">
            Post to YouTube
        </button>
    </div>
</form>

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Rates.cshtml
@{
    ViewBag.Title = "Rates";
}

<form class="form-horizontal">
    <label class="control-label">
        Date
    </label>
    <div class="controls">
        <input type="text"/>
    </div>
    
    <div class="form-actions">
        <button type="submit" class="btn btn-large btn-primary">Submit</button>
    </div>
</form>

ParadiseBookers/ParadiseBookers.Web/Views/Properties/Websites.cshtml
@model ParadiseBookers.Models.Properties.PropertyViewModel

@{
    ViewBag.Title = "Websites";
}

<h2>Websites</h2>

ParadiseBookers/ParadiseBookers.Web/Views/Properties/_PropertyLayout.cshtml
@model ParadiseBookers.Models.Properties.PropertyViewModel

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/Basic.cshtml";
}

@section AltNav{
    
    <div class="pull-left">
         @Html.MvcSiteMap().Pills(SiteMap.Provider.FindSiteMapNodeFromKey("ManageProperties"), true,false)
    </div>

    <div class="btn-group pull-right">
        <a class="btn btn-inverse btn-large" href="@Url.Action("Manager")">Cancel</a>
    </div>
}


@RenderBody()
