ParadiseBookers/ParadiseBookers.Web/Models/Beaches/BeachViewModel.cs
using System.Data.Spatial;
using ParadiseBookers.Core.Common.Geography;
using ParadiseBookers.Models.Common;

namespace ParadiseBookers.Models.Beaches
{
    public class BeachViewModel
    {
        public BeachViewModel()
        {
            // some sample change
            Location = new AddressModel()
            {
                Address = "301 15th Street, Hood River",
                Location = GeographyHelpers.CreatePoint(45.7120903, -121.5272902)
            };
        }

        public AddressModel Location { get; set; }

        public string Name { get; set; }

        public bool Surfing { get; set; }

        public string Description { get; set; }

        public string SandType { get; set; }
    }
}

ParadiseBookers/ParadiseBookers.Web/Controllers/Beaches/BeachesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParadiseBookers.Core.Interfaces.Service;
using ParadiseBookers.Core.Model;
using ParadiseBookers.Models.Beaches;
using Omu.ValueInjecter;

namespace ParadiseBookers.Controllers.Beaches
{
    public class BeachesController : Controller
    {
        private readonly IBeachService _service;

        public BeachesController(IBeachService service)
        {
            _service = service;
        }

        //
        // GET: /Beaches/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Manager()
        {
            var model = _service.GetAll().ToList();
            return View(model);
        }

        public ActionResult Details(int id)
        {
            return View(new BeachViewModel());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new BeachViewModel());
        }

        [HttpPost]
        public ActionResult Create(BeachViewModel model)
        {
            if (ModelState.IsValid)
            {
                var beach = new Beach();
                beach.InjectFrom<UnflatLoopValueInjection>(model);
                _service.CreateBeach(beach);
                return RedirectToAction("Manager");
            }

            return View(model);
        }

        public ActionResult Photos(int id)
        {
            return View();
        }

    }
}

ParadiseBookers/ParadiseBookers.Web/Views/Beaches/Create.cshtml
@model ParadiseBookers.Models.Beaches.BeachViewModel

@{
    Bundles.Reference("googleMaps");
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Basic.cshtml";
}

@using (Html.BeginForm("Create", "Beaches", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true, "Unable to save property. Please correct the errors and try again.", new { @class = "alert alert-block alert-error" })

    @Html.EditorForModel()

    <div class="form-actions">
        <input type="submit" value="Save" class="btn btn-inverse btn-large" />
    </div>
}

ParadiseBookers/ParadiseBookers.Web/Views/Beaches/Details.cshtml
@model ParadiseBookers.Models.Beaches.BeachViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Basic.cshtml";
}


ParadiseBookers/ParadiseBookers.Web/Views/Beaches/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Basic.cshtml";
}

<h2>Index</h2>

ParadiseBookers/ParadiseBookers.Web/Views/Beaches/Manager.cshtml
@{
    ViewBag.Title = "Manager";
    Layout = "~/Views/Shared/Basic.cshtml";
}

@model IList<ParadiseBookers.Core.Model.Beach>

@section AltNav
{
    <div class="pull-right">
        <a href="@Url.Action("Create", "Beaches")" class="btn btn-large">
            <i class="icon-plus"></i>
            New Beach
        </a>
    </div>

}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Title</th>
            <th>Owner</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var beach in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Details", "Beaches", new { id = beach.Id })">@beach.Id</a>
                </td>
                <td>
                    @beach.Name
                </td>
                <td>
                    <a href="#">sancho</a>
                </td>
            </tr>
        }

    </tbody>
</table>

ParadiseBookers/ParadiseBookers.Web/Views/Beaches/Photos.cshtml
@{
    ViewBag.Title = "Photos";
    Layout = "~/Views/Shared/Basic.cshtml";
}

<h2>Photos</h2>

ParadiseBookers/ParadiseBookers.Web/Views/Beaches/_BeachLayout.cshtml
@model ParadiseBookers.Models.Beaches.BeachViewModel

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/Basic.cshtml";
}

@section AltNav{
    
    <div class="pull-left">
         @Html.MvcSiteMap().Pills(SiteMap.Provider.FindSiteMapNodeFromKey("ManageBeaches"), true,false)
    </div>

    <div class="btn-group pull-right">
        <a class="btn btn-inverse btn-large" href="@Url.Action("Manager")">Cancel</a>
    </div>
}


@RenderBody()
